### PR TITLE
[CHANGED] `const int` to `int` for `Count` field in lists

### LINKED ISSUE #545: C++: natsMsgList default constructor is a deleted function
The following line of code fails to compile using VS2022 (Win SDK 8.1)

```cplusplus
natsMsgList list;
```
with error: 
natsMsgList::natsMsgList(void)': attempting to reference a deleted function

'natsMsgList::natsMsgList(void)': function was implicitly deleted because 'natsMsgList' has an uninitialized const-qualified data member 'natsMsgList::Count'

Any thoughts on how to fix this?

### PR DESCRIPTION
**Pull request by kozlovic**
This was causing compilation errors in C++ and was not really
adding any protection. It is stated in the doc that this value
should not be changed by the user prior to calling the destroy
function for those various lists.

Resolves #545

Signed-off-by: Ivan Kozlovic <ivan@synadia.com>

### CODE REVIEW

**Review by aricart — APPROVED** [review]
LGTM
